[jenkins]
i-0eff032df0235cbd8

[docker_host]
i-03b09d0b7b22a34fe

[all:vars]
ansible_connection=aws_ssm
ansible_aws_ssm_region=us-east-1
ansible_aws_ssm_bucket_name=3bslam-ansible-ssm-transfer
ansible_user=ec2-user
become=true
become_method=sudo
